*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 10.01.2019 at 08:00:08 by user PAULS
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZMP_PV_PARTNER..................................*
FORM GET_DATA_ZMP_PV_PARTNER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM SBUSPART WHERE
(VIM_WHERETAB) .
    CLEAR ZMP_PV_PARTNER .
ZMP_PV_PARTNER-MANDANT =
SBUSPART-MANDANT .
ZMP_PV_PARTNER-BUSPARTNUM =
SBUSPART-BUSPARTNUM .
ZMP_PV_PARTNER-CONTACT =
SBUSPART-CONTACT .
ZMP_PV_PARTNER-CONTPHONO =
SBUSPART-CONTPHONO .
ZMP_PV_PARTNER-BUSPATYP =
SBUSPART-BUSPATYP .
    SELECT SINGLE * FROM STRAVELAG WHERE
AGENCYNUM = SBUSPART-BUSPARTNUM .
    IF SY-SUBRC EQ 0.
ZMP_PV_PARTNER-NAME =
STRAVELAG-NAME .
ZMP_PV_PARTNER-STREET =
STRAVELAG-STREET .
ZMP_PV_PARTNER-POSTBOX =
STRAVELAG-POSTBOX .
ZMP_PV_PARTNER-POSTCODE =
STRAVELAG-POSTCODE .
ZMP_PV_PARTNER-CITY =
STRAVELAG-CITY .
ZMP_PV_PARTNER-COUNTRY =
STRAVELAG-COUNTRY .
ZMP_PV_PARTNER-REGION =
STRAVELAG-REGION .
ZMP_PV_PARTNER-TELEPHONE =
STRAVELAG-TELEPHONE .
ZMP_PV_PARTNER-URL =
STRAVELAG-URL .
ZMP_PV_PARTNER-LANGU =
STRAVELAG-LANGU .
ZMP_PV_PARTNER-CURRENCY =
STRAVELAG-CURRENCY .
    ENDIF.
<VIM_TOTAL_STRUC> = ZMP_PV_PARTNER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMP_PV_PARTNER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMP_PV_PARTNER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMP_PV_PARTNER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM SBUSPART WHERE
  BUSPARTNUM = ZMP_PV_PARTNER-BUSPARTNUM .
    IF SY-SUBRC = 0.
    DELETE SBUSPART .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM STRAVELAG WHERE
    AGENCYNUM = SBUSPART-BUSPARTNUM .
    IF SY-SUBRC = 0.
    DELETE STRAVELAG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM SBUSPART WHERE
  BUSPARTNUM = ZMP_PV_PARTNER-BUSPARTNUM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR SBUSPART.
    ENDIF.
SBUSPART-MANDANT =
ZMP_PV_PARTNER-MANDANT .
SBUSPART-BUSPARTNUM =
ZMP_PV_PARTNER-BUSPARTNUM .
SBUSPART-CONTACT =
ZMP_PV_PARTNER-CONTACT .
SBUSPART-CONTPHONO =
ZMP_PV_PARTNER-CONTPHONO .
SBUSPART-BUSPATYP =
ZMP_PV_PARTNER-BUSPATYP .
    IF SY-SUBRC = 0.
    UPDATE SBUSPART .
    ELSE.
    INSERT SBUSPART .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM STRAVELAG WHERE
    AGENCYNUM = SBUSPART-BUSPARTNUM .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR STRAVELAG.
STRAVELAG-AGENCYNUM =
SBUSPART-BUSPARTNUM .
      ENDIF.
STRAVELAG-NAME =
ZMP_PV_PARTNER-NAME .
STRAVELAG-STREET =
ZMP_PV_PARTNER-STREET .
STRAVELAG-POSTBOX =
ZMP_PV_PARTNER-POSTBOX .
STRAVELAG-POSTCODE =
ZMP_PV_PARTNER-POSTCODE .
STRAVELAG-CITY =
ZMP_PV_PARTNER-CITY .
STRAVELAG-COUNTRY =
ZMP_PV_PARTNER-COUNTRY .
STRAVELAG-REGION =
ZMP_PV_PARTNER-REGION .
STRAVELAG-TELEPHONE =
ZMP_PV_PARTNER-TELEPHONE .
STRAVELAG-URL =
ZMP_PV_PARTNER-URL .
STRAVELAG-LANGU =
ZMP_PV_PARTNER-LANGU .
STRAVELAG-CURRENCY =
ZMP_PV_PARTNER-CURRENCY .
    IF SY-SUBRC = 0.
    UPDATE STRAVELAG .
    ELSE.
    INSERT STRAVELAG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMP_PV_PARTNER-UPD_FLAG,
STATUS_ZMP_PV_PARTNER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMP_PV_PARTNER.
  SELECT SINGLE * FROM SBUSPART WHERE
BUSPARTNUM = ZMP_PV_PARTNER-BUSPARTNUM .
ZMP_PV_PARTNER-MANDANT =
SBUSPART-MANDANT .
ZMP_PV_PARTNER-BUSPARTNUM =
SBUSPART-BUSPARTNUM .
ZMP_PV_PARTNER-CONTACT =
SBUSPART-CONTACT .
ZMP_PV_PARTNER-CONTPHONO =
SBUSPART-CONTPHONO .
ZMP_PV_PARTNER-BUSPATYP =
SBUSPART-BUSPATYP .
    SELECT SINGLE * FROM STRAVELAG WHERE
AGENCYNUM = SBUSPART-BUSPARTNUM .
    IF SY-SUBRC EQ 0.
ZMP_PV_PARTNER-NAME =
STRAVELAG-NAME .
ZMP_PV_PARTNER-STREET =
STRAVELAG-STREET .
ZMP_PV_PARTNER-POSTBOX =
STRAVELAG-POSTBOX .
ZMP_PV_PARTNER-POSTCODE =
STRAVELAG-POSTCODE .
ZMP_PV_PARTNER-CITY =
STRAVELAG-CITY .
ZMP_PV_PARTNER-COUNTRY =
STRAVELAG-COUNTRY .
ZMP_PV_PARTNER-REGION =
STRAVELAG-REGION .
ZMP_PV_PARTNER-TELEPHONE =
STRAVELAG-TELEPHONE .
ZMP_PV_PARTNER-URL =
STRAVELAG-URL .
ZMP_PV_PARTNER-LANGU =
STRAVELAG-LANGU .
ZMP_PV_PARTNER-CURRENCY =
STRAVELAG-CURRENCY .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZMP_PV_PARTNER-NAME .
      CLEAR ZMP_PV_PARTNER-STREET .
      CLEAR ZMP_PV_PARTNER-POSTBOX .
      CLEAR ZMP_PV_PARTNER-POSTCODE .
      CLEAR ZMP_PV_PARTNER-CITY .
      CLEAR ZMP_PV_PARTNER-COUNTRY .
      CLEAR ZMP_PV_PARTNER-REGION .
      CLEAR ZMP_PV_PARTNER-TELEPHONE .
      CLEAR ZMP_PV_PARTNER-URL .
      CLEAR ZMP_PV_PARTNER-LANGU .
      CLEAR ZMP_PV_PARTNER-CURRENCY .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMP_PV_PARTNER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMP_PV_PARTNER-BUSPARTNUM TO
SBUSPART-BUSPARTNUM .
MOVE ZMP_PV_PARTNER-MANDANT TO
SBUSPART-MANDANT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'SBUSPART'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN SBUSPART TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'SBUSPART'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE SBUSPART-BUSPARTNUM TO
STRAVELAG-AGENCYNUM .
MOVE ZMP_PV_PARTNER-MANDANT TO
STRAVELAG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'STRAVELAG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN STRAVELAG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'STRAVELAG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
